"""Output marking — AI Act Article 50.

Article 50 is the obligation that did *not* move. The Digital Omnibus agreed in
May 2026 deferred the Annex III high-risk regime to 2 December 2027 and the
Annex I regime to 2 August 2028, but the transparency duties — telling people
they are interacting with an AI system, and marking synthetic output in a
machine-readable way — applied from 2 August 2026 and still do. Most
organisations spent the spring celebrating the deferral and stopped reading.

Two markings are produced, because they answer to different readers:

* a **machine-readable manifest**, detached, binding the output digest to the
  model card digest and to the journal entry that recorded the inference;
* a **human-readable disclosure**, a short sentence intended to be rendered
  next to the output where a person will see it.

The manifest deliberately carries digests rather than payloads: it can be
published, attached, or forwarded without disclosing the input. A provenance
scheme that forces you to disclose the data in order to prove the provenance
will not survive contact with a DPO.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from ..canonical import digest, digest_bytes
from ..clock import Clock, SystemClock, iso

PROVENANCE_SCHEMA = "governed-edge-ai/provenance/v1"

DEFAULT_DISCLOSURE = "Result generated by an automated AI system."


@dataclass(frozen=True)
class MarkedOutput:
    """An output plus the two markings that must travel with it."""

    output: Any
    output_digest: str
    manifest: dict[str, Any]
    disclosure: str

    def to_record(self) -> dict[str, Any]:
        """Journal-ready form: digests and manifest, never the payload."""
        return {
            "output_digest": self.output_digest,
            "manifest_digest": digest(self.manifest),
            "disclosure": self.disclosure,
        }


class OutputMarker:
    """Attaches provenance to every output of an admitted model."""

    def __init__(
        self,
        *,
        device_id: str,
        model_id: str,
        model_version: str,
        card_digest: str,
        disclosure: str = DEFAULT_DISCLOSURE,
        clock: Clock | None = None,
    ) -> None:
        self.device_id = device_id
        self.model_id = model_id
        self.model_version = model_version
        self.card_digest = card_digest
        self.disclosure = disclosure or DEFAULT_DISCLOSURE
        self.clock = clock or SystemClock()

    def mark(
        self,
        output: Any,
        *,
        input_digest: str | None = None,
        journal_entry_hash: str | None = None,
        synthetic: bool = True,
    ) -> MarkedOutput:
        """Produce the manifest and disclosure for one output."""
        output_digest = (
            digest_bytes(output) if isinstance(output, (bytes, bytearray))
            else digest(output)
        )
        manifest = {
            "schema": PROVENANCE_SCHEMA,
            "synthetic": synthetic,
            "generated_at": iso(self.clock.now()),
            "generated_by": {
                "device_id": self.device_id,
                "model_id": self.model_id,
                "model_version": self.model_version,
                "card_digest": self.card_digest,
            },
            "output_digest": output_digest,
            "input_digest": input_digest,
            "journal_entry": journal_entry_hash,
            "disclosure": self.disclosure,
        }
        return MarkedOutput(
            output=output,
            output_digest=output_digest,
            manifest=manifest,
            disclosure=self.disclosure,
        )


def verify_marking(manifest: Any, output: Any) -> tuple[bool, str]:
    """Check that a manifest actually describes ``output``.

    Returns ``(ok, reason)``. A marking nobody can check is a marking nobody
    will trust; this is the function a downstream consumer runs.
    """
    if not isinstance(manifest, dict) or manifest.get("schema") != PROVENANCE_SCHEMA:
        return False, f"not a {PROVENANCE_SCHEMA} manifest"
    for field in ("output_digest", "generated_by", "generated_at", "disclosure"):
        if field not in manifest:
            return False, f"manifest missing {field!r}"
    expected = (
        digest_bytes(output) if isinstance(output, (bytes, bytearray)) else digest(output)
    )
    if manifest["output_digest"] != expected:
        return False, "manifest does not describe this output (digest mismatch)"
    generator = manifest["generated_by"]
    for field in ("device_id", "model_id", "model_version", "card_digest"):
        if not generator.get(field):
            return False, f"manifest generated_by.{field} is empty"
    return True, "manifest matches the output"
