"""A deterministic end-to-end scenario.

This is the demonstration the repository exists for: a weld-inspection cell that
cannot start itself, cannot exceed its declared operating envelope, cannot
divert a part it is unsure about without a named human, cannot restart itself
after a fault, and cannot spend more than it was allocated, with a journal that
proves each of those five refusals happened.

Everything is seeded, so two runs on two machines produce identical journals
apart from timestamps, and timestamps come from an injected clock.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from ..canonical import digest_file
from ..clock import FrozenClock
from ..hal.sim import SimulatedCell, SimulatedModel
from ..journal import Journal
from ..marking import verify_marking
from ..oversight import (
    CompositeStopChannel,
    HardwareStopChannel,
    ScriptedConfirmer,
    SoftwareStopChannel,
    Supervisor,
)
from ..policy import ActuationRequest, BudgetLedger, PolicyEngine
from ..registry import SigningKey, TrustStore, sign_card
from .runtime import ActionOutcome, GovernedRuntime

DEMO_EPOCH = datetime(2026, 8, 21, 9, 0, 0, tzinfo=timezone.utc)

#: Seed chosen (openly) so that one demonstration run exercises both the
#: low-confidence escalation path and the consecutive-defect stop. Cherry-picking
#: a seed to make a demo work is only dishonest when you do not say so; the tests
#: pin other seeds, including ones where nothing interesting happens.
DEMO_SEED = 12
POLICY_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
    "policies",
    "inspection.json",
)


def demo_card(artifact_digest: str) -> dict[str, Any]:
    return {
        "schema": "governed-edge-ai/model-card/v1",
        "model_id": "weld-defect-detector",
        "version": "1.4.0",
        "artifact_digest": artifact_digest,
        "risk_tier": "high",
        "intended_purpose": (
            "Detect visual weld defects on parts passing an inspection station "
            "and divert defective parts from the line."
        ),
        "out_of_scope_uses": [
            "Any assessment of the operator rather than the weld.",
            "Safety certification of the finished assembly.",
            "Operation below 200 lux without human confirmation.",
        ],
        "provider": {
            "name": "Glossolalie Advisory (showcase)",
            "contact": "governance@example.org",
        },
        "deployment": {"targets": ["ventuno-q", "uno-q", "sim"], "runtime": "onnx"},
        "data": {
            "training_data_summary": "12,400 labelled weld images, 3 production lines",
            "personal_data": False,
        },
        "evaluation": {
            "metrics": {"precision": 0.94, "recall": 0.89},
            "evaluated_at": "2026-07-30T00:00:00Z",
            "known_limitations": [
                "Accuracy degrades below 200 lux.",
                "Not evaluated above 0.4 m/s belt speed.",
            ],
        },
        "oversight": {"human_in_the_loop": True, "stop_channel_required": True},
        "transparency": {
            "marks_synthetic_output": True,
            "disclosure_text": (
                "Automated visual inspection, this result was generated by an AI system."
            ),
        },
        "controls_required": ["inference_journal", "policy_mediation"],
        "valid_from": "2026-08-01T00:00:00Z",
        "valid_until": "2027-08-01T00:00:00Z",
    }


@dataclass
class Bench:
    """Everything wired together, ready to run."""

    runtime: GovernedRuntime
    cell: SimulatedCell
    model: SimulatedModel
    clock: FrozenClock
    journal: Journal
    trust_store: TrustStore
    envelope: dict[str, Any]
    artifact_path: str


def build_bench(
    workdir: str,
    *,
    confirmations: list[bool] | None = None,
    budgets: dict[str, float] | None = None,
    operator_id: str = "operator-01",
    policy_path: str | None = None,
    miss_rate: float = 0.0,
    seed: int = DEMO_SEED,
    defect_rate: float = 0.35,
) -> Bench:
    """Assemble a fully governed runtime over the simulated cell."""
    os.makedirs(workdir, exist_ok=True)
    clock = FrozenClock(DEMO_EPOCH)

    artifact_path = os.path.join(workdir, "weld-detector-1.4.0.bin")
    with open(artifact_path, "wb") as handle:
        handle.write(b"a very small set of weights, for demonstration purposes")

    owner = SigningKey.generate("model-owner-01", "model_owner")
    risk = SigningKey.generate("risk-officer-01", "risk_officer")
    device = SigningKey.generate("device-sim-01", "operator")
    trust_store = TrustStore.from_keys(
        [owner, risk, device],
        datetime(2026, 1, 1, tzinfo=timezone.utc),
        datetime(2027, 12, 31, tzinfo=timezone.utc),
    )

    card = demo_card(digest_file(artifact_path))
    envelope = sign_card(card, [owner, risk], clock=clock)

    cell = SimulatedCell(seed=seed, defect_rate=defect_rate)
    journal = Journal(
        os.path.join(workdir, "journal.jsonl"),
        device_id="sim-cell-01",
        clock=clock,
        device_key=device,
        fsync=False,
    )
    policy = PolicyEngine.from_file(policy_path or POLICY_PATH)
    ledger = BudgetLedger(
        limits=budgets or {"actions": 40.0, "energy_j": 60.0},
        clock=clock,
    )
    supervisor = Supervisor(
        stop_channel=CompositeStopChannel(
            [SoftwareStopChannel(), HardwareStopChannel(cell.relay)]
        ),
        confirmer=ScriptedConfirmer(
            answers=confirmations if confirmations is not None else [True] * 20,
            operator_id=operator_id,
        ),
        clock=clock,
    )

    runtime = GovernedRuntime(
        envelope=envelope,
        trust_store=trust_store,
        device=cell,
        journal=journal,
        policy=policy,
        budgets=ledger,
        supervisor=supervisor,
        artifact_path=artifact_path,
        operator_id=operator_id,
        clock=clock,
    )
    return Bench(
        runtime=runtime,
        cell=cell,
        model=SimulatedModel(miss_rate=miss_rate),
        clock=clock,
        journal=journal,
        trust_store=trust_store,
        envelope=envelope,
        artifact_path=artifact_path,
    )


def run_scenario(workdir: str, *, parts: int = 12, **kwargs: Any) -> dict[str, Any]:
    """Run the demonstration and return a structured trace."""
    bench = build_bench(workdir, **kwargs)
    runtime, cell, model, clock = bench.runtime, bench.cell, bench.model, bench.clock
    trace: list[dict[str, Any]] = []

    def note(step: str, outcome: ActionOutcome | dict[str, Any]) -> None:
        if isinstance(outcome, ActionOutcome):
            trace.append(
                {
                    "step": step,
                    "performed": outcome.performed,
                    "effect": outcome.effect,
                    "reasons": list(outcome.reasons),
                }
            )
        else:
            trace.append({"step": step, **outcome})

    admission = runtime.open_session()
    trace.append(
        {
            "step": "admission",
            "admitted": admission.admitted,
            "obligations": list(admission.obligations),
            "signers": [f"{k} ({r})" for k, r in admission.signers],
        }
    )

    # The cell starts stopped: the relay is de-energised and the composite stop
    # channel is therefore engaged. Nothing the software can do releases it.
    note(
        "start_attempt_before_release",
        runtime.act(
            ActuationRequest(
                action="set_speed", target="cell", params={"speed": 0.3},
                requester="agent", rationale="begin the shift",
            )
        ),
    )

    note("operator_releases_stop", runtime.resume("operator-01"))
    clock.advance(seconds=1)

    note(
        "set_speed_within_envelope",
        runtime.act(
            ActuationRequest(
                action="set_speed", target="cell", params={"speed": 0.3},
                requester="agent", rationale="nominal belt speed for inspection",
            )
        ),
    )
    note(
        "set_speed_outside_envelope",
        runtime.act(
            ActuationRequest(
                action="set_speed", target="cell", params={"speed": 0.6},
                requester="agent",
                rationale="throughput is behind plan, run the belt faster",
            )
        ),
    )
    note(
        "action_on_foreign_target",
        runtime.act(
            ActuationRequest(
                action="set_speed", target="paint-booth", params={"speed": 0.2},
                requester="agent", rationale="the booth looks idle",
            )
        ),
    )
    note(
        "action_without_rationale",
        runtime.act(
            ActuationRequest(
                action="divert_part", target="cell",
                params={"serial": "P0000", "confidence": 0.99},
                requester="agent", rationale="",
            )
        ),
    )

    consecutive_defects = 0
    for _ in range(parts):
        clock.advance(seconds=2)
        observation = cell.sensors()["camera"].read()
        if observation.get("part") is None:
            trace.append({"step": "observe", "part": None, "reason": observation["reason"]})
            break

        marked = runtime.infer(observation, model)
        ok, reason = verify_marking(marked.manifest, marked.output)
        verdict = marked.output

        trace.append(
            {
                "step": "inference",
                "part": verdict["part"],
                "defect": verdict["defect"],
                "confidence": verdict["confidence"],
                "lux": verdict["lux"],
                "marking_verified": ok,
                "marking_reason": reason,
            }
        )

        if not verdict["defect"]:
            consecutive_defects = 0
            continue

        consecutive_defects += 1
        note(
            f"divert_{verdict['part']}",
            runtime.act(
                ActuationRequest(
                    action="divert_part",
                    target="cell",
                    params={"serial": verdict["part"], "confidence": verdict["confidence"]},
                    requester="agent",
                    model_id="weld-defect-detector",
                    rationale=(
                        f"model reported a defect on {verdict['part']} at "
                        f"{verdict['confidence']:.2f} confidence"
                    ),
                )
            ),
        )

        if consecutive_defects >= 3:
            note(
                "stop_on_defect_run",
                runtime.act(
                    ActuationRequest(
                        action="stop_conveyor",
                        target="cell",
                        params={"reason": "three consecutive defects, upstream fault"},
                        requester="agent",
                        rationale="a run of defects indicates a process fault upstream",
                    )
                ),
            )
            break

    report = runtime.report()
    closing = runtime.close_session()
    return {
        "trace": trace,
        "report": report,
        "closing": closing,
        "journal_path": bench.journal.path,
        "trust_store": bench.trust_store.to_document(),
    }


def write_scenario_artifacts(workdir: str, result: dict[str, Any]) -> dict[str, str]:
    """Persist the trace and the trust store next to the journal."""
    trace_path = os.path.join(workdir, "trace.json")
    store_path = os.path.join(workdir, "trust-store.json")
    with open(trace_path, "w", encoding="utf-8") as handle:
        json.dump(
            {"trace": result["trace"], "report": result["report"]},
            handle, indent=2, ensure_ascii=False,
        )
    with open(store_path, "w", encoding="utf-8") as handle:
        json.dump(result["trust_store"], handle, indent=2)
    return {"trace": trace_path, "trust_store": store_path}
